# Site settings
title: DealerOn Candidate Tests
email: alberto@dealeron.com
description: DealerOn Candidate Tests Repo
baseurl: "/candidate/" # the subpath of your site, e.g. /blog/
url: ""

# Build settings
permalink: :categories/:title.html
markdown: kramdown

kramdown:
  auto_ids: false

gems:
- jekyll-compass